services:
  nextjs-app:
    build:
      context: .
      dockerfile: docker/nextjs/Dockerfile.dev
    volumes:
      - ./nextjs:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"  # Direct access for development
    command: npm run dev

  media-processor:
    volumes:
      - ./python:/app/python:ro
    environment:
      - DEBUG=1
      - PYTHONUNBUFFERED=1